### ISSUE TITLE
Consider using an "real" Engine.

### ISSUE THREAD

**Issue by intrigus** [NinjaPhase/PokeDroid#1]
I think that I would be easier to use a real Engine like libgdx, that also has cross-platfrom support.
You also would not have to rewrite everything from scratch.
Libgdx is written in Java so it shouldn't be to hard to switch if you want.

There's also an irc channel #libgdx on https://freenode.net/.
If you want I can help you a little bit, if you want to switch.

**Comment by NinjaPhase** [comment]
Thanks for the suggestion, I will be switching to libGDX shortly and have been messing around with it before you mentioned this, this will open up android support for YAPJE (which i'm looking forward to as an android use myself). By real engine I assume you mean one more suited towards a graphical games with OpenGL support.
